### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Dangerise** [dsy4567/4399-on-vscode#12]
![image](https://user-images.githubusercontent.com/88434542/193438131-8cfc27f5-efa1-4583-8094-591e6cfeae9a.png)

加油 ！

**Comment by dsy4567** [comment]
麻烦点一下最上面的 帮助 \> 打开开发人员工具, 提供一下错误日志, 谢谢

**Comment by Dangerise** [comment]
![image](https://user-images.githubusercontent.com/88434542/193443234-a90b95c0-40f0-4f8a-b295-7270d522cf2e.png)
不过这次游戏到能成功运行

**Comment by dsy4567** [comment]
建议登录一下  
按 Ctrl+shift+p, 找 4399 on vscode: 我的

**Comment by dsy4567** [comment]
已修复

**Comment by dsy4567** [comment]
跟进一下, 这个问题有没有再次出现?
